# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)

In [1]:

import numpy as np

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5])

print(my_arreglow)
print(np.mean(my_arreglow))


[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

### Antes de cualquier cosa importamos la libreria con alias

In [2]:
import numpy as np

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [3]:
# Solución (:
array_ceros = np.zeros((3, 4))
print(array_ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### **Ejercicio 2-  Suma de elementos:**
   Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [4]:
# Solucion :)
array = np.array([1, 2, 3, 4, 5])
suma = np.sum(array)
print(suma)

15


### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [5]:
array = np.array([10, 20, 30, 40, 50])

# Solución:)
maximo = np.max(array)
minimo = np.min(array)

print("Máximo:", maximo)
print("Mínimo:", minimo)

Máximo: 50
Mínimo: 10


### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [6]:
# Solución:)

array = np.array([10, 20, 30, 40, 50])
maximo = np.max(array)
minimo = np.min(array)

print("Máximo:", maximo)
print("Mínimo:", minimo)

Máximo: 50
Mínimo: 10


### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [8]:
# Solución:)

numeros_aleatorios = np.random.rand(5)
#Colocar sola la funcion genera números aleatorios de distribución uniforme en el intervalo [0.0, 1.0)
print(numeros_aleatorios)

[0.58866641 0.19038069 0.13692877 0.35522863 0.29130823]


### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [9]:
#Solucion:)
array = np.array([5, 10, 15, 20, 25])
promedio = np.mean(array)

print("Promedio:", promedio)

Promedio: 15.0


### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [10]:
#Solucion:)
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

C = np.concatenate((A, B))
print("Arreglo concatenado:", C)


Arreglo concatenado: [1 2 3 4 5 6]


### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [ ]:
#Solución:)
import numpy as np

array = np.array([10, 20, 30, 40, 50, 60, 70, 80])
matriz = array.reshape(4, 2)

print(matriz)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [14]:
#Solución:)
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

producto_punto = np.dot(A, B)
print("Producto punto:", producto_punto)

Producto punto: 32


### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [15]:
#Solución:)
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
matriz = array.reshape(2, 5)

print(matriz)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [ ]:
#Solucion :o
arr = np.array([9, 3, 6, 2, 1, 7])

## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = (retorno - inversión) / inversión * 100)*

In [18]:
# Solucion del ROIROIROIROIORIORI

# Estas son las inversiones que hicimos
inversiones = np.array([1000, 1500, 2000])

# Retornos obtenidos de ellas
retornos = np.array([1200, 1650, 1800])

# Fórmula ROI: ((retorno - inversión) / inversión) * 100
roi = (retornos - inversiones) / inversiones * 100

print("ROI x inversión:", roi)

ROI x inversión: [ 20.  10. -10.]


### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

In [19]:

# Dataset de precios 
precios = np.array([250, 320, 150, 500, 210])

min_valor = np.min(precios)
max_valor = np.max(precios)

# Normalización
normalizados = (precios - min_valor) / (max_valor - min_valor)

print("Precios normalizados:", normalizados)

Precios normalizados: [0.28571429 0.48571429 0.         1.         0.17142857]


### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

In [22]:

# Ventas del día
ventas = np.array([1200, 0, 750, 2400, 0, 1800])

# Elimincamos los dias en los que no se vendio 
dias_con_ventas = ventas[ventas > 0]

# Promedio
promedio = np.mean(dias_con_ventas)

# Reemplazamos los ceros por el promedio en VENTAS
ventas_filtradas = np.where(ventas == 0, promedio, ventas)

print("Se muestran las ventas con el promedio donde habia 0:", ventas_filtradas)

Se muestran las ventas con el promedio donde habia 0: [1200.  1537.5  750.  2400.  1537.5 1800. ]


### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

In [25]:

# Dataset 
presiones = np.array([120, 135, 140, 118, 150, 130, 160, 125, 142, 128])

# Calculando la media
media = np.mean(presiones)

# Desviación estándar 
de = np.std(presiones)

# Obtenemos los datos en el rango especificado
noRango = presiones[(presiones < 90) | (presiones > 140)]

print("Media:", media)
print("Desviación estándar:", de)
print("Presiones fuera del rango normal:", noRango)

Media: 134.8
Desviación estándar: 12.69488085804668
Presiones fuera del rango normal: [150 160 142]


### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

In [ ]:

# PIB 
pib = np.array([500, 320, 700, 450])

# Población
poblacion = np.array([10, 8, 12, 9])

# Formula PIB per cápita
pib_per_capita = pib / poblacion

# Buscando el pais con mayor indice
indice_mayor = np.argmax(pib_per_capita)

# Mostramos los resultados
print("PIB per cápita de cada país:", pib_per_capita)
print("El país con el mayor PIB per cápita es el número:", indice_mayor + 1)

### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```

